# Generated by Django 4.1.4 on 2022-12-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_comapany_company_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='comapany',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
